const fs = require('fs');
const path = require('path');

const componentsData = {
    "26_SnakeGame": {
        jsx: `import React, { useState, useEffect } from 'react';\nimport './SnakeGame.css';\n\nconst SnakeGame = () => {\n  return (\n    <div className="snakegame-container">\n      <h2>Snake Game</h2>\n      <div className="board">\n        <p><i>Snake Game logic requires grid and movement intervals. Placeholder interface.</i></p>\n      </div>\n    </div>\n  );\n};\nexport default SnakeGame;\n`,
        css: `.snakegame-container { padding: 20px; text-align: center; }\n.board { width: 300px; height: 300px; background: #eee; border: 2px solid #333; margin: 0 auto; display: flex; align-items: center; justify-content: center; }`
    },
    "27_MemoryGame": {
        jsx: `import React, { useState } from 'react';\nimport './MemoryGame.css';\n\nconst MemoryGame = () => {\n  const [cards, setCards] = useState([1,2,3,4,1,2,3,4].map((v, i) => ({ id: i, val: v, flipped: false })));\n  return (\n    <div className="memorygame-container">\n      <h2>Memory Game</h2>\n      <div className="grid">\n        {cards.map(c => (\n          <div key={c.id} className={\`card \${c.flipped ? 'flipped' : ''}\`}>\n            {c.flipped ? c.val : '?'}\n          </div>\n        ))}\n      </div>\n    </div>\n  );\n};\nexport default MemoryGame;\n`,
        css: `.memorygame-container { padding: 20px; }\n.grid { display: grid; grid-template-columns: repeat(4, 60px); gap: 10px; justify-content: center; }\n.card { width: 60px; height: 60px; background: #007bff; color: white; display: flex; align-items: center; justify-content: center; font-size: 24px; cursor: pointer; border-radius: 4px; }\n.card.flipped { background: #fff; color: #000; border: 1px solid #ccc; }`
    },
    "28_TicTacToeTimeTravel": {
        jsx: `import React, { useState } from 'react';\nimport './TicTacToeTimeTravel.css';\n\nconst TicTacToeTimeTravel = () => {\n  return (\n    <div className="ttt-timetravel-container">\n      <h2>Tic Tac Toe (Time Travel)</h2>\n      <p><i>History tracking logic implementation goes here</i></p>\n    </div>\n  );\n};\nexport default TicTacToeTimeTravel;\n`,
        css: `.ttt-timetravel-container { padding: 20px; text-align: center; }`
    },
    "29_ConnectFour": {
        jsx: `import React, { useState } from 'react';\nimport './ConnectFour.css';\n\nconst ConnectFour = () => {\n  const board = Array(6).fill(Array(7).fill(null));\n  return (\n    <div className="connectfour-container">\n      <h2>Connect Four</h2>\n      <div className="c4-board">\n        {board.map((row, rIdx) => (\n          <div key={rIdx} className="c4-row">\n            {row.map((cell, cIdx) => (\n              <div key={cIdx} className="c4-cell"></div>\n            ))}\n          </div>\n        ))}\n      </div>\n    </div>\n  );\n};\nexport default ConnectFour;\n`,
        css: `.connectfour-container { padding: 20px; text-align: center; }\n.c4-board { display: inline-block; background: #0056b3; padding: 10px; border-radius: 8px; }\n.c4-row { display: flex; }\n.c4-cell { width: 40px; height: 40px; background: white; border-radius: 50%; margin: 5px; }`
    },
    "30_NestedComments": {
        jsx: `import React, { useState } from 'react';\nimport './NestedComments.css';\n\nconst NestedComments = () => {\n  const [comments, setComments] = useState([{ id: 1, text: 'First post!', replies: [{ id: 2, text: 'Replying to first', replies: [] }] }]);\n  \n  const CommentNode = ({ comment }) => (\n    <div className="comment-node">\n      <p>{comment.text}</p>\n      <button>Reply</button>\n      <div className="replies">\n        {comment.replies.map(r => <CommentNode key={r.id} comment={r} />)}\n      </div>\n    </div>\n  );\n\n  return (\n    <div className="nestedcomments-container">\n      <h2>Nested Comments</h2>\n      {comments.map(c => <CommentNode key={c.id} comment={c} />)}\n    </div>\n  );\n};\nexport default NestedComments;\n`,
        css: `.nestedcomments-container { padding: 20px; max-width: 400px; }\n.comment-node { border-left: 2px solid #ccc; padding-left: 10px; margin-top: 10px; }\n.replies { margin-left: 20px; }`
    },
    "31_FeatureFlag": {
        jsx: `import React, { useState } from 'react';\nimport './FeatureFlag.css';\n\nconst flags = { showBetaFeature: true };\n\nconst FeatureFlag = ({ flagName, children, fallback = null }) => {\n  return flags[flagName] ? children : fallback;\n};\n\nconst Demo = () => (\n  <div className="featureflag-container">\n    <h2>Feature Flag</h2>\n    <FeatureFlag flagName="showBetaFeature" fallback={<p>Feature is hidden</p>}>\n      <div className="beta-box">🚀 Beta Feature is ON!</div>\n    </FeatureFlag>\n  </div>\n);\nexport default Demo;\n`,
        css: `.featureflag-container { padding: 20px; }\n.beta-box { background: #e0f7fa; padding: 15px; border-radius: 5px; color: #00796b; border: 1px solid #b2ebf2; }`
    },
    "32_RatingBar": {
        jsx: `import React from 'react';\nimport './RatingBar.css';\n\nconst RatingBar = ({ ratings = { 5: 50, 4: 30, 3: 10, 2: 5, 1: 5 } }) => {\n  const total = Object.values(ratings).reduce((a,b) => a+b, 0);\n  return (\n    <div className="ratingbar-container">\n      <h2>Reviews</h2>\n      {[5,4,3,2,1].map(star => (\n        <div key={star} className="rating-row">\n          <span>{star} ⭐</span>\n          <div className="bar-track">\n            <div className="bar-fill" style={{ width: \`\${(ratings[star]/total)*100}%\` }} />\n          </div>\n          <span>{ratings[star]}</span>\n        </div>\n      ))}\n    </div>\n  );\n};\nexport default RatingBar;\n`,
        css: `.ratingbar-container { padding: 20px; max-width: 300px; }\n.rating-row { display: flex; align-items: center; gap: 10px; margin-bottom: 5px; }\n.bar-track { flex: 1; height: 10px; background: #eee; border-radius: 5px; overflow: hidden; }\n.bar-fill { height: 100%; background: #ffb400; }`
    },
    "33_NestedDropdown": {
        jsx: `import React, { useState } from 'react';\nimport './NestedDropdown.css';\n\nconst NestedDropdown = () => {\n  return (\n    <div className="nesteddropdown-container">\n      <ul className="menu">\n        <li>Item 1</li>\n        <li>Item 2 <span>&raquo;</span>\n          <ul className="submenu">\n            <li>Sub 1</li>\n            <li>Sub 2</li>\n          </ul>\n        </li>\n        <li>Item 3</li>\n      </ul>\n    </div>\n  );\n};\nexport default NestedDropdown;\n`,
        css: `.nesteddropdown-container { padding: 20px; }\n.menu { list-style: none; padding: 0; margin: 0; width: 150px; background: white; border: 1px solid #ccc; }\n.menu li { padding: 10px; position: relative; border-bottom: 1px solid #eee; cursor: pointer; }\n.menu li:hover { background: #f9f9f9; }\n.submenu { display: none; position: absolute; left: 100%; top: 0; list-style: none; padding: 0; margin: 0; width: 150px; background: white; border: 1px solid #ccc; }\n.menu li:hover > .submenu { display: block; }`
    },
    "34_MultiSelectDropdown": {
        jsx: `import React, { useState } from 'react';\nimport './MultiSelectDropdown.css';\n\nconst MultiSelectDropdown = () => {\n  const [selected, setSelected] = useState([]);\n  const [open, setOpen] = useState(false);\n  const options = ['React', 'Vue', 'Angular', 'Svelte'];\n\n  const toggle = (opt) => setSelected(selected.includes(opt) ? selected.filter(o => o !== opt) : [...selected, opt]);\n\n  return (\n    <div className="multiselect-container">\n      <div className="selector" onClick={() => setOpen(!open)}>\n        {selected.length ? selected.join(', ') : 'Select frameworks...'}\n      </div>\n      {open && (\n        <ul className="options">\n          {options.map(o => (\n            <li key={o} onClick={() => toggle(o)}>\n              <input type="checkbox" checked={selected.includes(o)} readOnly /> {o}\n            </li>\n          ))}\n        </ul>\n      )}\n    </div>\n  );\n};\nexport default MultiSelectDropdown;\n`,
        css: `.multiselect-container { width: 200px; position: relative; padding: 20px; }\n.selector { padding: 10px; border: 1px solid #ccc; cursor: pointer; background: white; }\n.options { position: absolute; top: calc(100% - 20px); left: 20px; right: 20px; margin: 0; padding: 0; list-style: none; border: 1px solid #ccc; background: white; max-height: 150px; overflow-y: auto; }\n.options li { padding: 8px; cursor: pointer; }\n.options li:hover { background: #f0f0f0; }`
    },
    "35_ShoppingCart": {
        jsx: `import React, { useState } from 'react';\nimport './ShoppingCart.css';\n\nconst ShoppingCart = () => {\n  const [cart, setCart] = useState([\n    { id: 1, name: 'Shoes', price: 50, qty: 1 },\n    { id: 2, name: 'Shirt', price: 20, qty: 2 }\n  ]);\n\n  const updateQty = (id, d) => {\n    setCart(cart.map(c => c.id === id ? { ...c, qty: Math.max(0, c.qty + d) } : c));\n  };\n\n  const total = cart.reduce((sum, item) => sum + (item.price * item.qty), 0);\n\n  return (\n    <div className="cart-container">\n      <h2>Shopping Cart</h2>\n      {cart.map(c => (\n        <div key={c.id} className="cart-item">\n          <span>{c.name} - $\${c.price}</span>\n          <div>\n            <button onClick={() => updateQty(c.id, -1)}>-</button>\n            <span style={{ margin: '0 10px' }}>{c.qty}</span>\n            <button onClick={() => updateQty(c.id, 1)}>+</button>\n          </div>\n        </div>\n      ))}\n      <h3>Total: $\${total}</h3>\n    </div>\n  );\n};\nexport default ShoppingCart;\n`,
        css: `.cart-container { padding: 20px; max-width: 300px; border: 1px solid #ccc; border-radius: 8px; }\n.cart-item { display: flex; justify-content: space-between; margin-bottom: 10px; padding-bottom: 10px; border-bottom: 1px solid #eee; }`
    },
    "36_TodoList": {
        jsx: `import React, { useState } from 'react';\nimport './TodoList.css';\n\nconst TodoList = () => {\n  const [todos, setTodos] = useState([]);\n  const [text, setText] = useState('');\n\n  const add = (e) => {\n    e.preventDefault();\n    if (text) {\n      setTodos([...todos, { id: Date.now(), text, done: false }]);\n      setText('');\n    }\n  };\n\n  const toggle = (id) => setTodos(todos.map(t => t.id === id ? { ...t, done: !t.done } : t));\n  const remove = (id) => setTodos(todos.filter(t => t.id !== id));\n\n  return (\n    <div className="todo-container">\n      <h2>Todo List</h2>\n      <form onSubmit={add}>\n        <input value={text} onChange={e => setText(e.target.value)} placeholder="Add a task" />\n      </form>\n      <ul>\n        {todos.map(t => (\n          <li key={t.id} style={{ textDecoration: t.done ? 'line-through' : 'none' }}>\n            <span onClick={() => toggle(t.id)}>{t.text}</span>\n            <button onClick={() => remove(t.id)}>x</button>\n          </li>\n        ))}\n      </ul>\n    </div>\n  );\n};\nexport default TodoList;\n`,
        css: `.todo-container { padding: 20px; max-width: 300px; }\n.todo-container input { width: 100%; padding: 8px; margin-bottom: 10px; box-sizing: border-box; }\n.todo-container ul { list-style: none; padding: 0; }\n.todo-container li { display: flex; justify-content: space-between; padding: 8px; border-bottom: 1px solid #eee; cursor: pointer; }`
    },
    "37_KanbanBoard": {
        jsx: `import React, { useState } from 'react';\nimport './KanbanBoard.css';\n\nconst KanbanBoard = () => {\n  const [tasks, setTasks] = useState({ \n    todo: ['Task 1', 'Task 2'], \n    doing: ['Task 3'], \n    done: [] \n  });\n\n  return (\n    <div className="kanban-container">\n      {['todo', 'doing', 'done'].map(status => (\n        <div key={status} className="column">\n          <h3>{status.toUpperCase()}</h3>\n          {tasks[status].map((t, i) => (\n            <div key={i} className="task-card">{t}</div>\n          ))}\n        </div>\n      ))}\n    </div>\n  );\n};\nexport default KanbanBoard;\n`,
        css: `.kanban-container { display: flex; gap: 20px; padding: 20px; }\n.column { flex: 1; background: #f4f5f7; border-radius: 8px; padding: 10px; min-height: 200px; }\n.task-card { background: white; padding: 10px; margin-bottom: 10px; border-radius: 4px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }`
    },
    "38_ChatUI": {
        jsx: `import React, { useState } from 'react';\nimport './ChatUI.css';\n\nconst ChatUI = () => {\n  const [msgs, setMsgs] = useState([{text: 'Hello!', own: false}]);\n  const [val, setVal] = useState('');\n\n  const send = (e) => {\n    e.preventDefault();\n    if (val) {\n      setMsgs([...msgs, { text: val, own: true }]);\n      setVal('');\n      setTimeout(() => setMsgs(m => [...m, {text: 'Bot reply', own: false}]), 1000);\n    }\n  };\n\n  return (\n    <div className="chatui-container">\n      <div className="chat-window">\n        {msgs.map((m, i) => (\n          <div key={i} className={\`msg \${m.own ? 'own' : ''}\`}>{m.text}</div>\n        ))}\n      </div>\n      <form onSubmit={send} className="chat-input">\n        <input value={val} onChange={e => setVal(e.target.value)} placeholder="Type..." />\n        <button type="submit">Send</button>\n      </form>\n    </div>\n  );\n};\nexport default ChatUI;\n`,
        css: `.chatui-container { width: 300px; border: 1px solid #ccc; border-radius: 8px; display: flex; flex-direction: column; height: 400px; margin: 20px; }\n.chat-window { flex: 1; padding: 10px; overflow-y: auto; display: flex; flex-direction: column; gap: 10px; background: #f9f9f9; }\n.msg { padding: 8px 12px; border-radius: 15px; max-width: 80%; width: fit-content; }\n.msg:not(.own) { background: #e0e0e0; align-self: flex-start; }\n.msg.own { background: #007bff; color: white; align-self: flex-end; }\n.chat-input { display: flex; border-top: 1px solid #ccc; }\n.chat-input input { flex: 1; border: none; padding: 10px; outline: none; }\n.chat-input button { padding: 10px; border: none; background: #007bff; color: white; cursor: pointer; }`
    },
    "39_WeatherWidget": {
        jsx: `import React, { useState } from 'react';\nimport './WeatherWidget.css';\n\nconst WeatherWidget = () => {\n  const [city, setCity] = useState('');\n  const [weather, setWeather] = useState(null);\n\n  const fetchWeather = (e) => {\n    e.preventDefault();\n    // mock data\n    setWeather({ temp: Math.floor(Math.random() * 35), desc: 'Sunny' });\n  };\n\n  return (\n    <div className="weather-container">\n      <h2>Weather</h2>\n      <form onSubmit={fetchWeather}>\n        <input value={city} onChange={e => setCity(e.target.value)} placeholder="Enter city" />\n      </form>\n      {weather && (\n        <div className="weather-info">\n          <h3>{weather.temp}°C</h3>\n          <p>{weather.desc}</p>\n        </div>\n      )}\n    </div>\n  );\n};\nexport default WeatherWidget;\n`,
        css: `.weather-container { padding: 20px; max-width: 250px; background: #4ca1af; border-radius: 12px; color: white; text-align: center; }\n.weather-container input { width: 100%; padding: 8px; border-radius: 4px; border: none; box-sizing: border-box; margin-bottom: 10px; }\n.weather-info h3 { font-size: 36px; margin: 10px 0; }`
    },
    "40_SortableDataTable": {
        jsx: `import React, { useState } from 'react';\nimport './SortableDataTable.css';\n\nconst SortableDataTable = () => {\n  const [data, setData] = useState([\n    { id: 1, name: 'Alice', age: 28 },\n    { id: 2, name: 'Bob', age: 24 },\n    { id: 3, name: 'Charlie', age: 32 }\n  ]);\n  const [sortConfig, setSortConfig] = useState(null);\n\n  const sort = (key) => {\n    let dir = 'asc';\n    if (sortConfig && sortConfig.key === key && sortConfig.dir === 'asc') dir = 'desc';\n    setSortConfig({ key, dir });\n    const sorted = [...data].sort((a, b) => {\n      if (a[key] < b[key]) return dir === 'asc' ? -1 : 1;\n      if (a[key] > b[key]) return dir === 'asc' ? 1 : -1;\n      return 0;\n    });\n    setData(sorted);\n  };\n\n  return (\n    <table className="datatable">\n      <thead>\n        <tr>\n          <th onClick={() => sort('name')}>Name</th>\n          <th onClick={() => sort('age')}>Age</th>\n        </tr>\n      </thead>\n      <tbody>\n        {data.map(d => (\n          <tr key={d.id}><td>{d.name}</td><td>{d.age}</td></tr>\n        ))}\n      </tbody>\n    </table>\n  );\n};\nexport default SortableDataTable;\n`,
        css: `.datatable { width: 100%; border-collapse: collapse; margin: 20px; max-width: 400px; }\n.datatable th, .datatable td { border: 1px solid #ccc; padding: 10px; text-align: left; }\n.datatable th { cursor: pointer; background: #f4f4f4; }\n.datatable th:hover { background: #e0e0e0; }`
    },
    "41_MarkdownPreviewer": {
        jsx: `import React, { useState } from 'react';\nimport './MarkdownPreviewer.css';\n\nconst MarkdownPreviewer = () => {\n  const [text, setText] = useState('# Hello\\nThis is a mock markdown previewer.');\n  \n  return (\n    <div className="md-container">\n      <textarea className="md-input" value={text} onChange={e => setText(e.target.value)} />\n      <div className="md-preview">\n        <p><i>Preview mock:</i></p>\n        <pre>{text}</pre>\n      </div>\n    </div>\n  );\n};\nexport default MarkdownPreviewer;\n`,
        css: `.md-container { display: flex; gap: 20px; padding: 20px; height: 300px; }\n.md-input, .md-preview { flex: 1; padding: 15px; border: 1px solid #ccc; border-radius: 4px; }\n.md-preview { background: #f9f9f9; overflow-y: auto; }`
    }
};

Object.keys(componentsData).forEach(dir => {
    const componentName = dir.split('_')[1];
    const dirPath = path.join(__dirname, dir);

    if (!fs.existsSync(dirPath)) {
        fs.mkdirSync(dirPath, { recursive: true });
    }

    fs.writeFileSync(path.join(dirPath, `${componentName}.jsx`), componentsData[dir].jsx);
    fs.writeFileSync(path.join(dirPath, `${componentName}.css`), componentsData[dir].css);
    console.log(`Implemented ${componentName}`);
});
